### ISSUE TITLE
modbusParseRequest slave behavior

### ISSUE THREAD

**Issue by User330639** [Jacajack/liblightmodbus#15]
Greetings. You've made overall great and easy-to-use library. However, I recently came across the following issue (which might be not an issue, but caused my app to behave unexpectedly). The issue is as follows:

Having received full MODBUS frame, my app executes:
`if (MODBUS_OK == modbusParseRequest(&sstatus))
{
    // Do something with the data recieved
}`

modbusParseRequest returns MODBUS_OK (with no exceptions raised) if the address is either 0 or does not match the one of the slave. This lead to condition under 'if' being true upon reception of any valid frame. I managed to fix the issue for my app by changing the condition to

`(MODBUS_OK == modbusParseRequest(&sstatus) && sstatus.request.frame[0] == sstatus.address)`

I MIGHT have missed the exception being raised (why would I bother if the parser says that all is OK), but still.

Thanks.

**Comment by Jacajack** [comment]
If `modbusParseRequest()` returns OK, it means, quite literally, that there was no error. It may seem a bit weird, but the reasoning behind that was that it's fine to pick up frames meant for other slaves during communication. I hope that this makes the meaning of the error codes more clear, as they cannot be changed without breaking backward compatibility.

Your approach is perfectly valid, though. I don't know any details of your application, but you might want to add a check for the broadcast address too. If you want to go further and oversee individual coil/register operations the slave is asked to perform, you might want to try using a [register callback function](https://jacajack.github.io/liblightmodbus/register-callback.html).
