### ISSUE TITLE
status->registerCallback uses MODBUS_REGQ_R_CHECK where MODBUS_REGQ_W_CHECK should be used

### ISSUE THREAD

**Issue by DipSwitch** [Jacajack/liblightmodbus#16]
https://github.com/Jacajack/liblightmodbus/blob/2ced431d68fc32bd92a9243886dc0a2082f04bb5/src/slave/scoils.c#L181

In this line `MODBUS_REGQ_R_CHECK` should be replaced by `MODBUS_REGQ_W_CHECK` if I'm correct.

**Comment by Jacajack** [comment]
That's correct. Thanks for spotting this! :+1:
