### ISSUE TITLE
Modbus use for AVR 

### ISSUE THREAD

**Issue by Veloulou** [Jacajack/liblightmodbus#33]
Hello, 
I'm beginner and i want to use the modbus lib for an AVR128DA48 as a slave and i dont find / understand how to use your lib.
If you can help me to understand and find solutions.
best regards.

**Comment by Jacajack** [comment]
Hello, please take a look at the [examples directory](https://github.com/Jacajack/liblightmodbus/tree/master/examples). There you can find a simple example how to integrate the library into your project and full AVR slave source code.
